account/urls.py
from tempfile import template

from django.urls import re_path, path
from django.contrib.auth.views import LoginView, LogoutView
from . import views
from django.contrib.auth import views as auth_views

from .views import EmailConfirm

app_name = 'account'

urlpatterns = [
    re_path(r'^login/$', LoginView.as_view(), name='login'),
    re_path(r'^logout/$', views.user_logout, name='logout'),
    re_path(r'^logout-then-login/$', views.user_logout, name='logout_then_login'),
    re_path(r'^dashboard/$', views.dashboard, name='dashboard'),
    re_path(r'^password-change/$', views.change_password, name='password_change'),
    re_path(r'^password-change/done/$', views.password_change_done, name='password_change_done'),
    re_path(r'^password-reset/$',
            views.UserChangePassword,
            name='_password_reset'),
    re_path(r'^password-reset/done/$',
            views.PasswordResetForm,
            name='password_reset_done'),
    re_path(r'^password-reset/confirm/',
            EmailConfirm.as_view(),
            name='password_reset_confirm'),
    re_path(r'^password-reset/complete/$',
            auth_views.PasswordResetCompleteView.as_view(),
            name='password_reset_complete'),
    re_path(r'^registration/$', views.register, name='register'),
    re_path(r'^edit/$', views.edit, name='edit'),
]

pages1/urls.py
from django.urls import re_path, path

from . import views
from .views import post_detail

urlpatterns = [
    re_path(r'^$', views.PostListView.as_view(), name='post_list'),
    re_path(r'^tag/(?P<tag_slug>[-\w]+)/$', views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/', views.post_detail, name='post_detail'),
    re_path(r'^create/$', views.post_create, name='post_create'),
    path('<int:pk>/delete/', views.post_delete, name='post_delete'),
    path('reply_delete/<int:pk>/', views.reply_delete, name='reply_delete'),
    path('post_edit/<int:pk>/', views.post_edit, name='post_edit'),
]

stack2/urls.py
from lib2to3.fixes.fix_dict import iter_exempt

from django.contrib import admin
from django.urls import include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^posts/', include(('pages1.urls', 'posts'),
                       namespace='posts')),
    re_path(r'^account/', include(('account.urls', 'account'), namespace='account')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages1/models.py
from audioop import reverse
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from ckeditor.fields import RichTextField

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length = 250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='forum_posts')
    body = models.TextField()
    publish = models.DateTimeField(default = timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default = 'draft')

    tags = TaggableManager()

    def get_absolute_url(self):
        return f"/posts/{self.publish.year}/{self.publish.month:02}/{self.publish.day:02}/{self.slug}/"
    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title


class Reply(models.Model):
    post = models.ForeignKey(Post, related_name='replies', on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add = True)
    updated = models.DateTimeField(auto_now = True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)
    def __str__(self):
        return 'Reply by {} on {}'.format(self.name, self.post)

'''class Article(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length = 250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='forum_posts')
    body = RichTextField()
    publish = models.DateTimeField(default = timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default = 'draft')

    tags = TaggableManager()

    def get_absolute_url(self):
        return f"/articles/{self.publish.year}/{self.publish.month:02}/{self.publish.day:02}/{self.slug}/"
    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title'''

pages1/forms.py
from django import forms
from .models import Reply, Post


class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = ('name', 'email', 'body')

class ReplyFormLogin(forms.ModelForm):
    class Meta:
        model = Reply
        fields = ('body',)

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'tags', 'body')

class EditPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'tags', 'body')

pages1/views.py
import uuid
from datetime import timezone
from venv import logger

from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import AnonymousUser
from django.core.paginator import Paginator, PageNotAnInteger
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.text import slugify
from future.backports.datetime import datetime

from .forms import ReplyForm, PostForm, ReplyFormLogin, EditPostForm
from .models import Post, Reply
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView, DetailView
from taggit.models import Tag

def post_list(request, tag_slug=None):
    object_list = Post.objects.filter(status = 'published')
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)  # если номер страницы не целое число, показываем первую страницу
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)  # если страница выходит за пределы, показываем последнюю

    return render(request, 'posts/post/list.html', {
        'page': page,
        'posts': posts,
        'tag': tag
    })




def post_detail(request, year, month, day, slug):
    post = get_object_or_404(Post, slug=slug,
                             status = 'published',
                             publish__year = year,
                             publish__month = month,
                             publish__day = day)
    #reply_list
    replies = post.replies.filter(active = True)
    if request.method == 'POST':
        if request.user.is_authenticated:  # Авторизованный пользователь
            reply_form = ReplyFormLogin(data=request.POST)
            if reply_form.is_valid():
                new_reply = reply_form.save(commit=False)
                new_reply.name = request.user.username
                new_reply.email = request.user.email
                new_reply.post = post
                new_reply.save()
        else:  # Гость
            reply_form = ReplyForm(data=request.POST)
            if reply_form.is_valid():
                new_reply = reply_form.save(commit=False)
                new_reply.post = post
                new_reply.save()
    else:
        if request.user.is_authenticated:
            reply_form = ReplyFormLogin()
        else:
            reply_form = ReplyForm()
    return render(request, 'posts/post/details.html', {'post':post,
                                                                           'replies':replies,
                                                                           'reply_form': reply_form})
#create
@login_required
def post_create(request):
    if request.method == 'POST':
        post_form = PostForm(data=request.POST)
        if post_form.is_valid():
            new_post = post_form.save(commit=False)
            new_post.author = request.user
            new_post.status = 'published'
            new_post.slug = slugify(new_post.title)
            new_post.save()
            post_form.save_m2m()

            return redirect(new_post.get_absolute_url())

    else:
        post_form = PostForm
    return render(request, 'posts/post/create.html', {'post_form':post_form})

@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk, author=request.user)
    if request.method == 'POST':
        post_form = PostForm(instance=post)
        if post_form.is_valid():
            edit_post = post_form.save(commit=False)
            edit_post.slug = slugify(edit_post.title)
            edit_post.save()
            post_form.save_m2m()
            return redirect(edit_post.get_absolute_url())
    else:
        post_form = PostForm(instance=post)
    return render(request, 'posts/post/edit.html', {'post_form': post_form})

@login_required
def post_delete(request, pk):
    post = get_object_or_404(Post, pk=pk, author=request.user, )
    if request.method == 'POST':
        post.delete()
        return render(request, 'posts/post/delete.html')
    return redirect(request. post.get_absolute_url)

@login_required
def reply_delete(request, pk):
    reply = get_object_or_404(Reply, pk=pk, name=request.user.username)
    if request.method == 'POST':
        reply.delete()
        return render(request, f'posts/post/reply_delete.html')
    return redirect(request.reply.post.get_absolute_url)



class PostDetailView(DetailView):
    model = Post
    template_name = 'posts/post/detail.html'
    context_object_name = 'post'

class PostListView(ListView):
    queryset = Post.objects.filter(status = 'published')
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'posts/post/list.html'

pages1/templates/posts/base.html
<!DOCTYPE html>
{% load static %}
{% load posts_tags %}
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Default title {% endblock title %}</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
       <style>
       .sidebar{
            position: fixed;
            top: 0;
            right: -250px; /* Панель скрыта за правым краем */
            width: 250px;
            height: 100%;
            background-color: #343a40; /* Темный фон */
            color: white;
            transition: right 0.3s ease-in-out; /* Плавный выезд */
            z-index: 1050;
            padding: 20px;
       }

        .sidebar:hover {
            right: 0; /* Панель выезжает */
        }

        .sidebar-toggle {
            position: absolute;
            top: 50%;
            left: -50px;
            width: 50px;
            height: 50px;
            background-color: #343a40;
            color: white;
            text-align: center;
            line-height: 50px;
            border-radius: 50%;
            cursor: pointer;
            z-index: 1060;
        }

        .sidebar-toggle:hover {
            background-color: #495057;
        }

        .sidebar h3, .sidebar ul {
            padding-left: 20px;
        }

        .sidebar ul {
            list-style-type: none;
            padding-left: 20px;
        }

        .sidebar ul li a {
            color: white;
            text-decoration: none;
            padding: 5px 0;
            display: block;
        }

        .sidebar ul li a:hover {
            color: #ffc107;
        }
        body {
            background-color: #343a40; /* Цвет фона страницы */
            display: flex;
            justify-content: flex-start; /* Сместить контейнеры влево */
            align-items: center;
            height: 100vh;
            margin: 0;
            padding-left: 10%; /* Дополнительное смещение влево */
        }

        .form-container {
            background-color: #212529; /* Тёмный фон формы */
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.4);
            width: 400px;
            margin-right: 20px; /* Пространство между элементами */
        }

        /* Фон и текст полей формы */
        .form-control {
            background-color: #343a40 !important; /* Темный фон */
            color: #e9ecef !important;           /* Светлый текст */
            border: 1px solid #495057;           /* Границы */
        }
        .form-control:focus {
            border-color: #ffc107;               /* Желтая граница при фокусе */
            box-shadow: 0 0 4px #ffc107;         /* Лёгкое свечение */
        }
        /* Стили текста внутри формы */
        .form-container h2,
        .form-container p {
            color: #e9ecef;                      /* Светлый текст */
        }
        .form-group label {
            color: #e9ecef; /* Светлый цвет текста метки */
        }

        .form-group input,
        .form-group select,
        .form-group textarea {
            background-color: #343a40; /* Ещё более тёмный фон для полей */
            color: #e9ecef; /* Светлый текст */
            border: 1px solid #495057; /* Граница полей */
            border-radius: 4px;
            padding: 8px;
            width: 100%; /* Поля занимают всю ширину */
        }

        .form-group input:focus,
        .form-group select:focus,
        .form-group textarea:focus {
            outline: none;
            border-color: #ffc107; /* Подсветка при фокусе */
            box-shadow: 0 0 4px #ffc107;
        }

        input.btn-primary {
            background-color: #495057; /* Темная кнопка */
            color: #e9ecef;
            border-color: #495057;
        }

        input.btn-primary:hover {
            background-color: #ffc107;
            color: #343a40;
            border-color: #ffc107;
        }
    .btn-primary {
        position: relative;
        overflow: hidden;
        background-color: #495057; /* Начальный серый цвет */
        color: #e9ecef; /* Светлый цвет текста */
        border: 1px solid #495057; /* Граница */
        padding: 10px 20px;
        border-radius: 4px;
        cursor: pointer;
        transition: background-color 0.3s ease, color 0.3s ease; /* Плавный переход */
    }

    .btn-primary:hover {
        background-color: #ffc107; /* Оранжевый цвет при наведении */
        color: #343a40; /* Темный цвет текста */
    }

    .btn-primary::before {
        content: '';
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background: radial-gradient(circle, rgba(255, 193, 7, 0.5) 20%, transparent 60%);
        transform: scale(0);
        opacity: 0;
        transition: transform 0.5s ease-out, opacity 0.3s ease-out;
        z-index: 0; /* Позади текста */
    }

    .btn-primary:hover::before {
        transform: scale(3); /* Увеличение градиента */
        opacity: 1; /* Делает градиент видимым */
    }

    .btn-primary:focus {
        outline: none; /* Убирает синий контур при фокусе */
        box-shadow: none;
    }

        /* Карты */
        .container {
            margin: 0 auto; /* Центровка контейнера */
            padding: 20px;
            max-width: 1000px;
            overflow: visible; /* Обеспечивает видимость элементов */
        }

        .card {
            background-color: #343a40; /* Серый фон карты */
            color: white; /* Белый текст */
            border: 1px solid #495057; /* Светло-серая рамка */
            border-radius: 8px;
            max-width: 1000px;
            min-width: 1000px;
            padding: 20px;
            margin: 10px 0; /* Разделяет карты вертикально */
        }

        .cards-container {
            display: flex;
            flex-direction: column; /* Размещает карты в столбик */
            gap: 7px; /* Пространство между картами */
            margin-top: 50px; /* Убедитесь, что нет большого отступа сверху */
            padding-top: 20px; /* Отступ сверху для предотвращения перекрытия */
            height: 80vh; /* Контейнер занимает всю высоту окна */
            overflow: auto; /* Добавляет прокрутку, если контент превышает высоту */
            box-sizing: border-box; /* Включает отступы и границы в расчёт высоты */
        }

        .card h3 {
            margin-top: 0;
            color: #ffc107; /* Акцент на заголовке карты */
        }

        .card p {
            color: #e9ecef; /* Текст в карте */
        }
        .card small {
            display: block;
            margin-bottom: 10px;
            color: #adb5bd; /* Светло-серый для комментариев */
        }
        .form-delete {
            position: absolute;
            top: 10px;
            right: 10px;
            padding: 8px 16px;
        }
        .form-edit {
            position: absolute;
            top: 10px;
            right: 95px;
            padding: 8px 16px;
        }

        .form-back {
            position: absolute;
            top: 70px;
            left: 6px;
            padding: 9px 25px;
            width: 100%;
        }

        input.delete-button {
            position: absolute;
            top: 10px;
            right: 10px;
            padding: 8px 16px;
            background-color: rgba(128, 128, 128, 0.2); /* Серый с прозрачностью */
            color: red;
            border: 1px solid red;
            border-radius: 4px;
            font-size: 14px;
            font-weight: bold;
            text-decoration: none; /* Убирает подчеркивание */
            cursor: pointer;
            transition: background-color 0.3s, color 0.3s;
        }
        .edit-button {
            position: absolute;
            top: 20px;
            right: 110px;
            padding: 8px 16px;
            background-color: rgba(128, 128, 128, 0.2); /* Серый с прозрачностью */
            color: green;
            border: 1px solid green;
            border-radius: 4px;
            font-size: 14px;
            font-weight: bold;
            text-decoration: none; /* Убирает подчеркивание */
            cursor: pointer;
            transition: background-color 0.3s, color 0.3s;
        }

        .card .button:hover {
            background-color: red;
            color: #adb5bd;"
        }
        .static-header {
            position: fixed; /* Закрепляет <header> */
            top: 0;          /* Устанавливает <header> на верх страницы */
            left: 0;
            width: 100%;     /* Растягивает <header> на всю ширину */
            background-color: #343a40; /* Темный фон */
            color: #e9ecef;            /* Светлый текст */
            padding: 15px 20px;        /* Внутренние отступы */
            z-index: 1000;             /* Устанавливает высокий уровень слоя, чтобы <header> находился поверх других элементов */
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2); /* Добавляет тень для выделения */
}
    </style>
</head>
<body>
<header class="static-header">
    <a href="{% url "posts:post_list" %}" class="btn btn-primary">questions</a>
    {% if request.user.is_authenticated %}
        <a href="{% url "account:logout" %}" class="btn btn-primary">Logout</a>
        <a href="{% url "account:dashboard" %}" class="btn btn-primary">dashboard</a>
        <a href="{% url "account:edit" %}" class="btn btn-primary">your profile</a>
    {% else %}
        <a href="{% url "account:login" %}" class="btn btn-primary">Login</a>
    {% endif %}
</header>
    <!--<div class="sidebar-toggle">
        <span>&#8594;</span>
    </div>

     <div class="sidebar">
         <h3 class="text-center mt-2">Most pupular posts</h3>
            {% get_most_replied_posts as most_replied_posts %}
            {% for post in most_replied_posts %}
            <ul class="list-unstyled" >
            <li class="text-white">
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </li>
            </ul>
        {% endfor %}
    </div> !-->

    <div id = "content">
        {% block content %}
        {% endblock %}
    </div>


</body>
</html>